### ISSUE TITLE
URL Change

### ISSUE THREAD

**Issue by glipschitz** [BitschubserIT/dbus-shelly-3em-smartmeter#1]
/status is no longer valid

Code needs to be changed to use /rpc/Shelly.GetStatus

**Comment by glipschitz** [comment]
When you use /status this is the error;

`  File "/data/dbus/shelly-3em-grid40/shelly-3em-grid40.py", line 138, in _getShellyData
    raise ConnectionError("No response from Shelly 3EM - %s" % (URL))
ConnectionError: No response from Shelly 3EM - http://192.168.130.14/status`

When changing to /rpc/Shelly.GetStatus this is the error

`Traceback (most recent call last):
  File "/data/dbus/shelly-3em-grid40/shelly-3em-grid40.py", line 271, in main
    pvac_output = DbusShelly3emService(
  File "/data/dbus/shelly-3em-grid40/shelly-3em-grid40.py", line 66, in __init__
    self._dbusservice.add_path('/Serial', self._getShellySerial())
  File "/data/dbus/shelly-3em-grid40/shelly-3em-grid40.py", line 86, in _getShellySerial
    if not meter_data['mac']:
KeyError: 'mac'`

Hoping you can fix this one up :)
